### ISSUE TITLE
question: jsx to go

### ISSUE THREAD

**Issue by gedw99** [mamaar/gonads#3]
so it compiles jsx to js.
i was wondering if it can compile jsx to go. so that i can use the same react style of programming for non web apps.

**Comment by mamaar** [comment]
Hi,
This project was just put together to have a lightweight test server for developing a web front-end with SASS and JSX and doesn't really do anything else.
The project is also not being developed or maintained (I'm glad to merge pull requests if any) as I decided to go for [babel](http://babeljs.io/) instead.
